### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Magnatales** [defold/example-zig#3]
Windows 10
Tested in Defold 1.9.1 and 1.9.0

When I press F5 or ctrl + b I get this warning

![image](https://github.com/user-attachments/assets/91e664de-bee8-42c8-a7eb-ae600ba768c7)

Followed by this error:

System.UnauthorizedAccessException: Access to the path '/home/extender' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

com.defold.extender.ExtenderException: java.io.IOException: clang++ -DDLIB_LOG_DOMAIN="EXTENSIONCPP" -DDDF_EXPOSE_DESCRIPTORS -DDM_PLATFORM_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_CRT_USE_BUILTIN_OFFSETOF -D_WINSOCK_DEPRECATED_NO_WARNINGS -D__STDC_LIMIT_MACROS -DWINVER=0x0600 -DWIN32 -DNOMINMAX  -target x86_64-pc-win32-msvc -m64 -O2 -g -gcodeview -O2 -Wall -Werror=format -fvisibility=hidden -nostdinc++  -nostdinc++ -isystem /usr/lib/llvm-17/lib/clang/17/include -isystem /opt/platformsdk/Win32/MicrosoftVisualStudio2022/VC/Tools/MSVC/14.37.32822//include -isystem /opt/platformsdk/Win32/MicrosoftVisualStudio2022/VC/Tools/MSVC/14.37.32822//atlmfc/include -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.20348.0/ucrt -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.20348.0/winrt -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.20348.0/um -isystem /opt/platformsdk/Win32/WindowsKits/10//Include/10.0.20348.0/shared  -Ibuild/encoder_cpp/ -Iupload/  -I/var/extender/sdk/3be87d89fd5a93a63f527351fbedb84f8a875812/defoldsdk//include -I/var/extender/sdk/3be87d89fd5a93a63f527351fbedb84f8a875812/defoldsdk//sdk/include -I/var/extender/sdk/3be87d89fd5a93a63f527351fbedb84f8a875812/defoldsdk//ext/include  upload/encoder_cpp/src/encoder.cpp -c -o build/encoder.cpp_0.o

**Comment by JCash** [comment]
Unfortunately, only arm64-macos platform is supported by DotNet 9 at this moment. We will announce support for the Windows platform later on.
